### ISSUE TITLE
when i use the generated klg file, the ElasticFusion produced a error.

### ISSUE THREAD

**Issue by foolboyly** [HTLife/png_to_klg#7]
When i use the generated klg file, the ElasticFusion produced a error:' Not a JPEG file: starts with 0x6f 0x53'. I make sure the associations.txt is right. What should i solve this problem,please?

**Comment by HTLife** [comment]
Could you provide some portion of your associations.txt

**Comment by foolboyly** [comment]
I used the TUM dataset,'rgbd_dataset_freiburg1_360'. And i just test the your project's dataser 'livingroom_kt0_rs', the ElasticFusion produced another error:'  void RawLogReader::getCore(): Assertion `tmp' failed.
'.

1305031790.640468 depth/1305031790.640468.png 1305031790.645155 rgb/1305031790.645155.png
1305031790.672866 depth/1305031790.672866.png 1305031790.681208 rgb/1305031790.681208.png
1305031790.709421 depth/1305031790.709421.png 1305031790.713097 rgb/1305031790.713097.png
1305031790.739530 depth/1305031790.739530.png 1305031790.745223 rgb/1305031790.745223.png
1305031790.773548 depth/1305031790.773548.png 1305031790.781258 rgb/1305031790.781258.png
1305031790.809521 depth/1305031790.809521.png 1305031790.813207 rgb/1305031790.813207.png
1305031790.839363 depth/1305031790.839363.png 1305031790.845151 rgb/1305031790.845151.png
1305031790.871606 depth/1305031790.871606.png 1305031790.882094 rgb/1305031790.882094.png
1305031790.909436 depth/1305031790.909436.png 1305031790.913129 rgb/1305031790.913129.png
1305031790.941495 depth/1305031790.941495.png 1305031790.945171 rgb/1305031790.945171.png

**Comment by HTLife** [comment]
Haven saw this before.  Maybe you could use the debugger to found out other useful info.

**Comment by foolboyly** [comment]
thank you for your reply. I solved it. I modified the resolution when I used elasticfusion with kinect2. So I modified the   MainContorller.cpp and the resolution is 640 480.

**Comment by edith-langer** [comment]
Hi,

I get the same error with all the datasets I've tried (all have 640 by 480) and I use the original ElasticFusion code. 
I also tried Living Room 'lr kt0' which provides already an associations.txt file and that one works. When I run pngtoklg I do not need the option -t because the time stamps are integers, right?

For the test case you provide my associations.txt looks the following:
0 /home/edith/Software/png_to_klg/livingroom_kt0_rs/depth/scene_00_0000_rs.png 0 /home/edith/Software/png_to_klg/livingroom_kt0_rs/rgb/scene_00_0000_rs.png
1 /home/edith/Software/png_to_klg/livingroom_kt0_rs/depth/scene_00_0001_rs.png 1 /home/edith/Software/png_to_klg/livingroom_kt0_rs/rgb/scene_00_0001_rs.png
2 /home/edith/Software/png_to_klg/livingroom_kt0_rs/depth/scene_00_0002_rs.png 2 /home/edith/Software/png_to_klg/livingroom_kt0_rs/rgb/scene_00_0002_rs.png
3 /home/edith/Software/png_to_klg/livingroom_kt0_rs/depth/scene_00_0003_rs.png 3 /home/edith/Software/png_to_klg/livingroom_kt0_rs/rgb/scene_00_0003_rs.png
4 /home/edith/Software/png_to_klg/livingroom_kt0_rs/depth/scene_00_0004_rs.png 4 /home/edith/Software/png_to_klg/livingroom_kt0_rs/rgb/scene_00_0004_rs.png
5 /home/edith/Software/png_to_klg/livingroom_kt0_rs/depth/scene_00_0005_rs.png 5 /home/edith/Software/png_to_klg/livingroom_kt0_rs/rgb/scene_00_0005_rs.png

The paths to the images are correct, I checked that.
I added some additional output in the RawLogReader::getCore() function. Image size is 921600 (which seems to be fine), but depth size is 0.

I do not know were the problem is...

**Update**: 
Solved it by having the associations.txt in the same folder as depth and rgb folders and not using absolute pathes....

**Comment by HTLife** [comment]
@edith-langer cool!  Sorry for let you spending time on path problem.
